### PR TITLE
Jess review card

### PR DESCRIPTION
**Pull request by JessBonanno**
- Using data from the API to populate cards
- Can mark a review as helpful 
- Created select with needed options for review sorting

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Finish the Review Cards](https://trello.com/c/GeTO4OnD/13-finish-the-review-cards)

**Review by dsuh95 — COMMENTED** [review]
Pulled locally, everything seems to be working

**Review by jyxsul — APPROVED** [review]
Approved. Works locally.

**Review by dsuh95 — APPROVED** [review]
Looks good

**Pull request merged**
