### PR TITLE
Jess reviews

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

Added mobile and tablet styles to make reviews components responsive

## Type of change ##

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Part of a feature.
- [x] Refactor (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist ##

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] added new dependencies
- [ ] added tests
- [ ] updated documentation
- [x] Looks good on large screens
- [x] Looks good on mobile

## Organization ##

- [x] Have you linked this pull request to a Trello card?

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[ensure reviews component is responsive](https://trello.com/c/D6N81R8Q/37-ensure-reviews-component-is-responsive)

**Comment by JessBonanno** [comment]
[allow users to mark more than 1 review as helpful or reported](https://trello.com/c/rtXL5dfY/39-allow-users-to-mark-more-than-1-review-as-helpful-or-reported)

**Comment by JessBonanno** [comment]
[update reviews viewing when filtering by star rating](https://trello.com/c/DBUsz8Y3/50-update-reviews-viewing-when-filtering-by-star-rating)

**Review by DManthonyx — APPROVED** [review]
Looks good and nice with add the responsiveness

**Review by dsuh95 — APPROVED** [review]
Pulled locally, other than the one test failing, looks good

**Pull request merged**
