### PR TITLE
Jess reviews ratings

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

Created the ratings side bar with full functionality to match spec

## Type of change ##

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Part of a feature.
- [ ] Refactor (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist ##

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] added new dependencies
- [ ] added tests
- [ ] updated documentation
- [x] Looks good on large screens
- [ ] Looks good on mobile

## Organization ##

- [x] Have you linked this pull request to a Trello card?

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Create Product breakdown (factors) component L](https://trello.com/c/EJVVLRvr/35-create-product-breakdown-factors-component-l)

**Comment by JessBonanno** [comment]
[Create Ratings Breakdown component and recommendations percentage L](https://trello.com/c/CpsHkBcz/34-create-ratings-breakdown-component-and-recommendations-percentage-l)

**Comment by JessBonanno** [comment]
[Hook up sorting dropdown to be functional M](https://trello.com/c/8QSbqlEj/26-hook-up-sorting-dropdown-to-be-functional-m)

**Comment by JessBonanno** [comment]
[Create the Rating Summary Component SM](https://trello.com/c/ZzGRVrAY/16-create-the-rating-summary-component-sm)

**Review by jyxsul — APPROVED** [review]
Approved looks great. Maybe try to center the overall component instead of justifying to the left.

**Review by dsuh95 — APPROVED** [review]
Pulled locally, looks good

**Pull request merged**
