### PR TITLE
Jess testing

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

- Installed and configured jest and enzyme for testing
- began writing tests for the ratings and reviews components

## Type of change ##

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Part of a feature.
- [ ] Refactor (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist ##

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] added new dependencies
- [x] added tests
- [ ] updated documentation
- [ ] Looks good on large screens
- [ ] Looks good on mobile

## Organization ##

- [ ] Have you linked this pull request to a Trello card?

## Review ##

- [x] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[Create tests for the Review widget](https://trello.com/c/5oo3t9nu/22-create-tests-for-the-review-widget)

**Review by jyxsul — APPROVED** [review]
Approved. Tests pass. Looks great

**Review by dsuh95 — APPROVED** [review]
Pulled locally, tests run well

**Review by DManthonyx — APPROVED** [review]
Looks good

**Pull request merged**
