### PR TITLE
Click tracker

### PR DESCRIPTION
**Pull request by JessBonanno**
## Description ##

Created click tracker in APIContext and added it to all interactions in Ratings and Reviews components
- fixed broken test
- added testing to PR template

## Type of change ##

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Part of a feature.
- [ ] Refactor (non-breaking change which does not add functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist ##

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] added new dependencies
- [x] added tests
- [ ] updated documentation
- [x] Looks good on large screens
- [x] Looks good on mobile

## Organization ##

- [x] Have you linked this pull request to a Trello card?

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by JessBonanno** [comment]
[fix broken test in reviewBreakdown](https://trello.com/c/GLhsrqRX/51-fix-broken-test-in-reviewbreakdown)

**Comment by JessBonanno** [comment]
[Implement Click tracker](https://trello.com/c/qdnoCDTT/52-implement-click-tracker)

**Review by dsuh95 — APPROVED** [review]
Pulled locally, I see the interactions call on the network tab on click, Nice work

**Review by DManthonyx — APPROVED** [review]
Looks great

**Pull request merged**
